language: objective-c

before_install:
  - gem install xcpretty

osx_image: xcode9

env:
  global:
    - PROJECT=jenkinsTest.xcodeproj
    - SCHEME=jenkinsTest
    - SDK=iphonesimulator11.0
  matrix:
    - DESTINATION="OS=11.0,name=iPhone 8"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  - xcodebuild
    -xcode_project "$PROJECT"
    -scheme "$SCHEME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Debug
    ONLY_ACTIVE_ARCH=YES
    clean test | xcpretty -c;

  - xcodebuild
    -xcode_project "$PROJECT"
    -scheme "$SCHEME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Release
    ONLY_ACTIVE_ARCH=YES
    ENABLE_TESTABILITY=YES
    clean test | xcpretty -c;