language: objective-c

before_install:
  - gem install xcpretty

osx_image: xcode9

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  - xcodebuild
    -project jenkinsTest
    -scheme jenkinsTest
    -sdk iphonesimulator11.0
    -destination "OS=11.0,name=iPhone 8"
    -configuration Debug
    ONLY_ACTIVE_ARCH=YES
    clean test | xcpretty -c;

  - xcodebuild
    -project jenkinsTest
    -scheme jenkinsTest
    -sdk iphonesimulator11.0
    -destination "OS=11.0,name=iPhone 8"
    -configuration Release
    ONLY_ACTIVE_ARCH=YES
    ENABLE_TESTABILITY=YES
    clean test | xcpretty -c;